name: .NET Core Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '#skip_ci')"
     
    strategy:
      matrix:
        os: [ubuntu-16.04, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.7.0
      with:
        dotnet-version: 3.1.301
    - name: install versioning tool
      run: dotnet tool install --tool-path . nbgv
    - name: Install dependencies
      run: dotnet restore
    - name: Build Core
      run: dotnet build --configuration Release --no-restore src/ExpressionPowerTools.Core/ExpressionPowerTools.Core.csproj
    - name: Build Serialization
      run: dotnet build --configuration Release --no-restore src/ExpressionPowerTools.Serialization/ExpressionPowerTools.Serialization.csproj
    - name: Build AspNetCore EF Core Middleware
      run: dotnet build --configuration Release --no-restore src/ExpressionPowerTools.Serialization.EFCore.AspNetCore/ExpressionPowerTools.Serialization.EFCore.AspNetCore.csproj
    - name: Build EF Core Http Client
      run: dotnet build --configuration Release --no-restore src/ExpressionPowerTools.Serialization.EFCore.Http/ExpressionPowerTools.Serialization.EFCore.Http.csproj
  
