name: .NET Core Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip_ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 3.1.401
    - name: Run all tests
      run: dotnet test ExpressionPowerTools.sln --logger trx