name: .NET Core Sample Builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#skip_ci')"
     
    steps:
    - uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.2
      with:
        dotnet-version: 3.1.301
    - name: install versioning tool
      run: dotnet tool install --tool-path . nbgv
    - name: Install dependencies
      run: dotnet restore samples/Blazor/SimpleBlazorWasm/SimpleBlazorWasm.sln
    - name: Build Simple Blazor WebAssembly sample
      run: dotnet build --configuration Release --no-restore samples/Blazor/SimpleBlazorWasm/SimpleBlazorWasm.sln
