name: .NET Core Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '#skip_ci')"

    steps:
    - uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: install versioning tool
      run: dotnet tool install --tool-path . nbgv
    - name: Install dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --no-restore --logger trx

