# This is a basic workflow that is manually triggered

name: Pack and Publish NuGet

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   
  build-and-package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Fetch
      run: git fetch --unshallow
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 3.1.301
    - name: install versioning tool
      run: dotnet tool install --tool-path . nbgv
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Core Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ExpressionPowerTools.Core/ExpressionPowerTools.Core.csproj
        TAG_COMMIT: false
        VERSION_STATIC: true
        NUGET_KEY: ${{ secrets.NUGET_EXPRESSION }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
    - name: Serialization Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ExpressionPowerTools.Serialization/ExpressionPowerTools.Serialization.csproj
        TAG_COMMIT: false
        VERSION_STATIC: true
        NUGET_KEY: ${{ secrets.NUGET_EXPRESSION }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
    - name: EF Core AspNet Core Middleware Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ExpressionPowerTools.Serialization.EFCore.AspNetCore/ExpressionPowerTools.Serialization.EFCore.AspNetCore.csproj
        TAG_COMMIT: false
        VERSION_STATIC: true
        NUGET_KEY: ${{ secrets.NUGET_EXPRESSION }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
    - name: EF Core Http Client Package
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: src/ExpressionPowerTools.Serialization.EFCore.Http/ExpressionPowerTools.Serialization.EFCore.Http.csproj
        TAG_COMMIT: false
        VERSION_STATIC: true
        NUGET_KEY: ${{ secrets.NUGET_EXPRESSION }}
        # Flag to toggle pushing symbols along with nuget package to the server, disabled by default
        INCLUDE_SYMBOLS: true
